name: "Hadolint Test"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
      
      - name: Lint Dockerfile (Hadolint)
        id: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: warning.Dockerfile
          # config: config/hadolint.yaml
          no-fail: true
          verbose: true
     
      - name: Hadolint results
        env:
          results: ${{ steps.hadolint.outputs.results }}
        run: |
          echo ${{ steps.hadolint.outcome }}
          
          printf "\nHadolint Results:\n"
          echo "$results"
